#!/usr/bin/env perl

use v5.18;

use File::Basename;
use File::Spec;
my $dirname;
BEGIN { $dirname = dirname(File::Spec->rel2abs( __FILE__ )) }
use lib "$dirname/local/lib/perl5";
use lib "$dirname/lib";

use Getopt::Long;

=head1 SYNOPSIS

play_icfp2015 -f problem.json -p cthulu

  -f  FILENAME  File containing JSON encoded input
  -t  NUMBER    Time limit, in seconds, to produce output
  -m  NUMBER    Memory limit, in megabytes, to produce output
  -c  NUMBER    Number of processor cores available
  -p  STRING    Phrase of power

CUSTOM OPTIONS

  -b STRING     Command to run bot

=cut

my (@filenames, $timelimit, $memlimit, $cores, @phrases, $bot);

$bot = "./randbot-valid.pl";

Getopt::Long::Configure("bundling");
Getopt::Long::Configure("auto_help");
GetOptions(
  "filename|f=s" => \@filenames,
  "timeout|t=i"  => \$timelimit,
  "memout|m=i"   => \$memlimit,
  "cores|c=i"    => \$cores,
  "phrase|p=s"   => \@phrases,
  "bot|b=s"      => \$bot,
);

@phrases = map { $_ =~ s/'/'"'"'/g; $_ } @phrases;
my $power_params = join(" ", map { "-p " . "'$_'" } @phrases);
# say "cmd: ./bleh $power_params";
# say `echo ./bleh $power_params`;
# say `perl -E 'foreach my \$a (\@ARGV) { say "->\$a" }' -- $power_params`;
# say `echo perl -E 'foreach my \$a (\@ARGV) { say "->\$a" }' -- $power_params`;
# exit;

my @results;

foreach my $problem (@filenames) {
  my $results = `./verify.pl --contest-mode $power_params $problem $bot`;
  push @results, split(/\n/, $results);
}

print "[";
print join(",", @results);
print "]\n";

