#!/usr/bin/env perl

use v5.18;

use File::Basename;
use File::Spec;
my $dirname;
BEGIN { $dirname = dirname(File::Spec->rel2abs( __FILE__ )) }
use lib "$dirname/local/lib/perl5";
use lib "$dirname/lib";

use Getopt::Long;

=head1 SYNOPSIS

play_icfp2015 -f problem.json -s cthulu

  -f  FILENAME  File containing JSON encoded input
  -t  NUMBER    Time limit, in seconds, to produce output
  -m  NUMBER    Memory limit, in megabytes, to produce output
  -c  NUMBER    Number of processor cores available
  -p  STRING    Phrase of power

=cut

my (@filenames, $timelimit, $memlimit, $cores, @phrases);

Getopt::Long::Configure("bundling");
Getopt::Long::Configure("auto_help");
GetOptions(
  "filename|f=s" => \@filenames,
  "timeout|t=i"  => \$timelimit,
  "memout|m=i"   => \$memlimit,
  "cores|c=i"    => \$cores,
  "phrase|p=s"   => \@phrases,
);

my @results;

foreach my $problem (@filenames) {
  my $results = `./verify.pl --contest-mode $problem ./randbot-valid.pl`;
  push @results, split(/\n/, $results);
}

print "[";
print join(",", @results);
print "]\n";

